# Use OpenJDK image as the base
FROM openjdk:17-jdk-alpine

# Set the working directory
WORKDIR /app

# Copy necessary files
COPY .mvn/ .mvn
COPY mvnw .
COPY pom.xml .

# Ensure the Maven wrapper script has execute permissions
RUN chmod +x ./mvnw

# Download dependencies
RUN ./mvnw dependency:go-offline -B

# Copy the rest of the project
COPY src ./src

# Build the application
RUN ./mvnw package -DskipTests

# Specify the command to run the application
CMD ["java", "-jar", "target/your-app.jar"]

